---
services:
  asr:
    build: ./asr/
    volumes:
      - "./model_cache_asr:/home/user/.cache:rw"
    networks:
      - nginx-bridge
    environment:
      - VIRTUAL_HOST=${ASR_VIRTUAL_HOST:-sapolita.ithuan.tw}
      - LETSENCRYPT_HOST=${ASR_VIRTUAL_HOST:-sapolita.ithuan.tw}
  asr-kaldi:
    build: ./asr-kaldi/
    volumes:
      - "./model_cache_asr_kaldi:/home/user/.cache:rw"
    networks:
      - nginx-bridge
    environment:
      - VIRTUAL_HOST=${ASR_KALDI_VIRTUAL_HOST:-sapolita-kaldi.ithuan.tw}
      - LETSENCRYPT_HOST=${ASR_KALDI_VIRTUAL_HOST:-sapolita-kaldi.ithuan.tw}
  tts:
    build: ./tts/
    volumes:
      - "./model_cache_tts:/home/user/.cache:rw"
    networks:
      - nginx-bridge
    environment:
      - VIRTUAL_HOST=${TTS_VIRTUAL_HOST:-hnang-kari-ai-asi-sluhay.ithuan.tw}
      - LETSENCRYPT_HOST=${TTS_VIRTUAL_HOST:-hnang-kari-ai-asi-sluhay.ithuan.tw}

networks:
  nginx-bridge:
    external: true
